.Dd $Mdocdate$
.Dt SOCKS 1
.Sh NAME
.Nm socks
.Nd UCSPI socks proxy client
.Sh SYNOPSIS
.Nm tcpclient
.Ar proxy-host
.Ar proxy-port Nm socks
.Ar host
.Ar port
.Ar program
.Op arguments
.Sh DESCRIPTION
The
.Nm
utility is a socks proxy handler for a UCSPI execchain.
It communicates with tcpclient over pipes with filedescriptor 6 and 7.
tcpclient connects to the socks proxy and delegates the further protocol
handling to
.Nm socks .
socks talks with the socks proxy and initiates a tcp connection to
.Ar host
with
.Ar port .
After connection initiation
.Nm
executes
.Ar program
with
.Ar arguments .
.Sh ENVIRONMENT
The following environment variables are defined in the UCPSI specification.
By the usage of
.Nm socks
there are two TCP connections.
One from the
.Nm tcpclient
to the socks proxy and an other from the socks proxy to the server.
The
.Nm socks
programm tries to handel this in a transparant way for the program.
All variables which are set from tcpclient to describe the TCP connection
between program and proxy are overwritten with the description of the TCP
connection between proxy and server.
Additionally variables are set to describe the connection between program
and proxy.


   SOCKSLOCAL   TCPLOCAL
        |          |
 program <--> proxy <--> server
             |          |
        SOCKSREMOTE  TCPREMOTE

.Bl -tag -width Ds
.It Ev PROTO
Is set to TCP.
.It Ev TCPLOCALHOST Ev TCPLOCALIP Ev TCPLOCALPORT
These variables are set to the hostname, IP address and port number of the
local socks proxy address.
.It Ev TCPREMOTEHOST Ev TCPREMOTEIP Ev TCPREMOTEPORT
These variables are set to the hostname, IP address and port number of the
server.
.It Ev SOCKSLOCALHOST Ev SOCKSLOCALIP Ev SOCKSLOCALPORT
These variables are set to the hostname, IP address and port number of the
tcpclient local side.
.It Ev SOCKSREMOTEHOST Ev SOCKSREMOTEIP Ev SOCKSREMOTEPORT
These variables are set to the hostname, IP address and port number of the
socks proxy server side.
.El
.\".Sh EXIT STATUS
.\".Sh EXAMPLES
.Sh SEE ALSO
.Xr tcpclient 1 ,
.Xr socks 1
.Sh STANDARDS
RFC 1928, SOCKS version 5
.Sh AUTHORS
This program was written by Jan Klemkow.
