.Dd April 3, 2016
.Dt TLSC 1
.Os
.Sh NAME
.Nm tlsc
.Nd UCSPI TLS Client
.Sh SYNOPSIS
.Nm tcpclient Ar host Ar port Nm tlsc
.Op Fl hsCHTV
.Op Fl F Ar fingerprint
.Op Fl n Ar hostname
.Op Fl c Ar cert_file
.Op Fl f Ar ca_file
.Op Fl p Ar ca_path
.Ar program
.Op args...
.Sh DESCRIPTION
The
.Nm
utility is a TLS client to be used in an UCSPI exec-chains.
.Nm
initializes the TLS tunnel an checks the server side certificate.
The certificate verification can be controlled by to following options.
The system CA certificates are used to verify the current connection
certificate by default.
With
.Fl f
.Nm
verifies the certificate chain based on one of the CA certificates stored in
.Ar ca_file
It is also possible to set a directory of CA certificate as trusted base with
.Fl p .
The options are as follows:
.Bl -tag -width Ds
.It Fl h
Show usage text.
.It Fl s
Show the servers certificate information and exits.
.It Fl c
Uses first private key in
.Ar cert_file
for client site authentication.
.It Fl f Ar cafile
.Ar cafile
is a file of CA certificates in PEM format.
The file can contain several CA certificates.
.It Fl p Ar capath
.Ar capath
is a directory containing CA certificates in PEM format.
The files each contain one CA certificate.
.It Fl n Ar hostname
Uses
.Ar hostname
for hostname verification.
.It Fl F Ar fingerprint
sets the hash of the server certificate.
If the hash does not match than the connection is about after handshake.
.It Fl H
Disables hostname verification.
.It Fl C
Disables certificate chain verification.
.It Fl T
Disables time verification.
.It Fl V
Disables certificate verification in general.
.El
.Sh ENVIRONMENT
.Bl -tag -width Ds
.It TLSC_FINGERPRINT
contains the server certificate's fingerprint.
.It TLSC_NO_VERIFICATION
turns of all kind of certificate verification.
.It TLSC_NO_HOST_VERIFICATION
turns of verification of the certificate hostname.
.It TLSC_NO_CERT_VERIFICATION
turns of verification of the certificate chain.
.It TLSC_NO_TIME_VERIFICATION
turns of verification of the certificate validation time.
.El
.Sh EXIT STATUS
.Ex -std
.Sh SEE ALSO
.Xr socks 1 ,
.Xr tcpclient 1
.Sh AUTHORS
.An -nosplit
The
.Nm
program was written by
.An Jan Klemkow Aq Mt j.klemkow@wemelug.de .
